--Insertamos algunos registros para que la base de datos no este vacia 

INSERT INTO HOTEL(NOMBRE, DESTINO, CAPACIDAD, OCUPACION, ESTADO) VALUES ('Melia-Madrid-Princesa','Madrid',274,190,1);
INSERT INTO HOTEL(NOMBRE, DESTINO, CAPACIDAD, OCUPACION, ESTADO) VALUES ('Gran-Melia-Palacio-de-los-Duques','Madrid',180,89,1);
INSERT INTO HOTEL(NOMBRE, DESTINO, CAPACIDAD, OCUPACION, ESTADO) VALUES ('Melia-White-House','Londres',581,492,1);
INSERT INTO HOTEL(NOMBRE, DESTINO, CAPACIDAD, OCUPACION, ESTADO) VALUES ('ME-London','Londres',157,100,1);
INSERT INTO HOTEL(NOMBRE, DESTINO, CAPACIDAD, OCUPACION, ESTADO) VALUES ('Innside-Paris-Charles-de-Gaulle','Paris',278,100,1);
INSERT INTO HOTEL(NOMBRE, DESTINO, CAPACIDAD, OCUPACION, ESTADO) VALUES ('Melia-Paris-La-Defense','Paris',369,322,1);
INSERT INTO HOTEL(NOMBRE, DESTINO, CAPACIDAD, OCUPACION, ESTADO) VALUES ('TRYP-New-York-Times-Square','Nueva-York',173,62,1);
INSERT INTO HOTEL(NOMBRE, DESTINO, CAPACIDAD, OCUPACION, ESTADO) VALUES ('Innside-New-York-Nomad','Nueva-York',313,183,1);

INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('68060671Z','Sergio','Cuenca','Nuñez','scuenca@gmail.com','2000-02-8');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('35980493Y','Ana','alvarez','Perez','aa@yahoo.com','2000-06-3');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('74575576P','Laura','Hernandez','Medem','laurah@gmail.com','2000-08-27');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('73010655F','Gerardo','Fernandez','Gomez','ag@gmail.com','2000-03-12');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('38421952S','Soraya','Conderana','Sicilia','sorayita@gmail.com','2000-03-12');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('56808995F','Elena','Garcia','Santamaria','ele@gmail.com','2000-09-12');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('86104585Z','Isabel','Gonzalez','Casado','isaa@gmail.com','2000-09-9');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('87504295J','Jaime','Lopez','Ayuso','jla@gmail.com','2000-09-9');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('93528386J','Gerardo','Pascual','Sanchez','gpas@gmail.com','2000-11-9');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('48802294C','Dario','Quiroga','Iglesias','dario.q@gmail.com','2000-11-3');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('24215194N','Esteban','Selles','Ferriz','esteban.s.f@gmail.com','2000-12-3');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('85630933R','Leo','Zamora','Mateos','xxleo@yahoo.com','2000-12-6');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('67756676X','Pablo','Leon','Abella','pablox@yahoo.com','2000-06-6');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('44203784S','Guillermo','Gutierrez','Vazquez','guti@yahoo.com','2000-04-6');
INSERT INTO CLIENTE(NIF, NOMBRE, APELLIDO1, APELLIDO2, CORREO, CUMPLEANOS) VALUES ('15979834D','Sara','alamo','Carrasco','alamosara@yahoo.com','2000-03-4');
